// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator_Extension
{
    internal sealed partial class Vsix
    {
        public const string Id = "Generator_Extension.3c7659fa-fecb-4683-bd50-c992786c1b74";
        public const string Name = "Generate C# Classes from Database";
        public const string Description = @"Extension for generating C# classes from database tables.";
        public const string Language = "en-US";
        public const string Version = "1.7.10";
        public const string Author = "Karlo Kranjčina";
        public const string Tags = "";
    }
}
